---
title: "Project Data"
format: html
editor: visual
---

This file is for loading and cleaning datasets. 

```{r setup}
#Load tidyverse packages for data cleaning
library(tidyverse)

```


## ACS (American Community Survey) Data Import
```{r import acs}
#Load the tidycensus package to connect to the US Census Bureau API
library(tidycensus)

#Set Census API to access data
census_key <- Sys.getenv("CENSUS_API_KEY")

#Load variables for 5 year ACS. Use view() function to browse.
all_vars <- load_variables(year = 2019, dataset = "acs5")

#Create list of state codes, needed for get_acs() function
states <- distinct(
  select(fips_codes, state)
  )

#Convert from dataframe to vector
states <- states[["state"]]

#remove codes for US territories
states <- states[1:51]

#Define variables to load from the American Community Survey
vars <- c(
  transport_mode_public_transit = "B08301_010",
  transport_mode_bike = "B08301_018",
  transport_mode_walk = "B08301_019",
  transport_mode_carpool = "B08301_004",
  commute_time = "B08303_001",
  median_household_income = "B19019_001"
)


#Load ACS data using the get_acs() function
census_bureau_data <- get_acs(
  geography = "tract",
  variables = vars,
  cache_table = TRUE,
  year = 2019,
  output = "wide",
  state = states,
  key = census_key,
  survey = "acs5"
)

```


## Other Data Import
```{r}

```

## Other Data Import
```{r}

```


## Combined Data
Here we combine individual datasets into our final dataset to be used for ML models called `transportation_data`.

```{r}

#Combine individual datasets into the final dataset
transportation_data <- census_bureau_data


#Export the final dataset to a .csv file
write.csv(transportation_data, file = "Transportation Data.csv")

```

